__title__ = 'damson'
__version__ = '0.6.0'
__description__ = 'A simple python validation library.'
__author__ = 'xasync'
__author_email__ = 'ixasync@outlook.com'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright Since 2019 xasync.com'
